# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-30 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happening', '0002_auto_20160802_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happeningsite',
            name='logo',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
