# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 18:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_pgjson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_data', django_pgjson.fields.JsonField(default={})),
                ('bio', models.TextField()),
                ('photo', models.ImageField(null=True, upload_to=None)),
                ('show_facebook_urls', models.BooleanField(default=False)),
                ('show_github_urls', models.BooleanField(default=False)),
                ('show_linkedin_urls', models.BooleanField(default=False)),
                ('show_twitter_urls', models.BooleanField(default=False)),
                ('show_google_urls', models.BooleanField(default=False)),
                ('show_stackexchange_urls', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='existing_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_data', django_pgjson.fields.JsonField(default={})),
                ('tag', models.CharField(max_length=100, unique=True)),
                ('users', models.ManyToManyField(related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrackingLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_data', django_pgjson.fields.JsonField(default={})),
                ('code', models.CharField(max_length=100, unique=True)),
                ('tags', models.ManyToManyField(related_name='tracking_links', to='members.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
