# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 14:52


from django.db import migrations, models
import django_pgjson.fields
import happening.storage


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_auto_20160128_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_data', django_pgjson.fields.JsonField(default={})),
                ('code', models.CharField(max_length=100, unique=True)),
                ('tags', models.ManyToManyField(related_name='tracking_links', to='members.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to=happening.storage.inner),
        ),
    ]
