# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import happening.storage


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20160117_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='restriction_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='restriction_filter',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to=happening.storage.inner),
        ),
    ]
