"""Appearance helpers."""

DEFAULT_THEME_SETTINGS = {
    "BACKGROUND-COLOR": "#EEF7FE",
    "HEADER-BACKGROUND-COLOR": "#1976D2",
    "SECONDARY-NAV-BACKGROUND-COLOR": "#BBDEFB",
    "SECONDARY-NAV-COLOR": "#3C6080",
    "BLOCK-COLOR": "#DEEFFC",
    "FONT-COLOR": "#3C6080",

    "MENU-COLOR": "#FFF",
    "MENU-HIGHLIGHT-BACKGROUND-COLOR": "#2196F3",
    "MENU-HIGHLIGHT-COLOR": "#FFF",

    "UNREAD-NOTIFICATION-BACKGROUND-COLOR": "#F52424",
    "UNREAD-NOTIFICATION-COLOR": "#FFF",

    "RADIO-BACKGROUND-COLOR": "#7FA9D2",
    "RADIO-COLOR": "#DEEFFC",
    "BUTTON-BACKGROUND-COLOR": "#1976D2",
    "BUTTON-COLOR": "#FFF",

    "MESSAGE-BACKGROUND-COLOR": "#DEEFFC",
    "ERROR-MESSAGE-BACKGROUND-COLOR": "#F52424",
    "SUCCESS-MESSAGE-BACKGROUND-COLOR": "#149A3E",
}
