language: python
python:
    - "2.7"
install:
    - pip install -r requirements.txt
    - pip install -r dev-requirements.txt
    - pip install coveralls
script: ./.run-ci
after_success:
    coveralls
before_script:
    - npm install -g bower
    - bower install
env: travis=true