language: python
services:
  - postgresql
python:
  - '2.7'
install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install coveralls
script: ./.run-ci
after_success: coveralls
before_script:
  - psql -c 'create database happening_test;' -U postgres
  - npm install -g bower
  - bower install
  - python manage.py migrate --noinput
env:
  - HAPPENING_TESTING=true DATABASE_URL='postgres://postgres:@localhost:5432/happening_test'
addons:
  postgresql: "9.3"