language: python
services:
  - postgresql
python:
  - '3.5.1'
install:
  - pip install -r src/requirements.txt
  - pip install -r src/dev-requirements.txt
  - pip install coveralls
  - npm install -g npm@2
script: ./src/.run-ci
after_success: coveralls
before_script:
  - psql -c 'create database happening_test;' -U postgres
  - npm install
  - python manage.py migrate --noinput
env:
  - HAPPENING_TESTING=true DATABASE_URL='postgres://postgres:@localhost:5432/happening_test'
addons:
  postgresql: "9.3"