language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install -r dev-requirements.txt
- pip install coveralls
script: ./.run-ci
after_success: coveralls
before_script:
- npm install -g bower
- ./setup
env: travis=true
deploy:
  provider: heroku
  api_key:
    secure: lXgNHi18FP6gA4lWztyvL9+nbIx9xkWqXPIrnKGrzMUbzOkvpoy2HSuHpTronyj/fEw25dx3xb56CyDNGsYTALbgJAIZUVWD4WgSeIWwnnXq9B1JgYDwuAf91qCVeyTk8a9k7zbqBszaiibzvde5JwB8R34AwSsRIkNwc+pLvaM=
  app: southamptoncodedojo
  on:
    repo: southampton-code-dojo/website
