#!/bin/sh
echo "Installing python dependencies";
if [ ! -d "ve" ]; then
    virtualenv ve;
fi

source ve/bin/activate;

pip install -r requirements.txt;
pip install -r dev-requirements.txt;

echo "Installing ruby dependencies";
gem install hologram

echo "Installing bower dependencies";
bower install;

python manage.py migrate;

python manage.py loaddata fixtures/common fixtures/users;

python manage.py generate_css