# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 18:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_pgjson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_data', django_pgjson.fields.JsonField(default={})),
                ('description', models.TextField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('success_url_name', models.CharField(max_length=255)),
                ('failure_url_name', models.CharField(max_length=255)),
                ('metadata', django_pgjson.fields.JsonField(default={})),
                ('extra', django_pgjson.fields.JsonField(default={})),
                ('_status', models.CharField(default='PENDING', max_length=7)),
                ('status_changed_datetime', models.DateTimeField(null=True)),
                ('_complete', models.BooleanField(default=False)),
                ('complete_datetime', models.DateTimeField(null=True)),
                ('error', models.TextField(null=True)),
                ('reciept_id', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_data', django_pgjson.fields.JsonField(default={})),
                ('description', models.CharField(max_length=255)),
                ('public_key', models.CharField(max_length=255)),
                ('secret_key', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
