# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-02 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20150602_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='_status',
            field=models.CharField(default='PENDING', max_length=7),
        ),
    ]
