# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-02 11:01
from __future__ import unicode_literals

from django.db import migrations
import django_pgjson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_page_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=django_pgjson.fields.JsonField(default={'blockLists': [[], []], 'blocks': []}),
        ),
    ]
