# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-02 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import happening.storage


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20160128_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to=happening.storage.inner),
        ),
    ]
