# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django_pgjson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_data', django_pgjson.fields.JsonField(default={})),
                ('restore', models.BooleanField(default=False)),
                ('started', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('complete_time', models.DateTimeField(null=True)),
                ('zip_file', models.FileField(null=True, upload_to=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PluginSetting',
            fields=[
                ('_data', django_pgjson.fields.JsonField(default={})),
                ('plugin_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
