# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-02 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import happening.storage


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20151123_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='zip_file',
            field=models.FileField(null=True, upload_to=happening.storage.inner),
        ),
    ]
