# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-30 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0005_auto_20160802_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='zip_file',
            field=models.FileField(null=True, upload_to=None),
        ),
    ]
