version: '2'
services:
  db:
    image: "postgres:latest"
  redis:
    image: "redis:latest"
  web:
    build:
      context: .
      dockerfile: web.dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:@db:5432/happening
      - REDIS_URL=redis://redis:6379
  celery:
    build:
      context: .
      dockerfile: celery.dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:@db:5432/happening
      - REDIS_URL=redis://redis:6379