#!/bin/sh
# Run from the correct directory
cd ${0%/*}
if [ ! -d "ve" ]; then
    echo "Error: Run ./setup first"
    exit
fi

export HAPPENING_TESTING="true";
source ve/bin/activate;
python manage.py test $1