#!/bin/sh
echo "Installing python dependencies";
if [ ! -d "ve" ]; then
    virtualenv -p python3 ve;
fi

source ve/bin/activate;

pip install -r requirements.txt;

echo "Installing ruby dependencies";
gem install hologram

echo "Installing npm dependencies";
npm install;

python manage.py migrate;

python manage.py loaddata fixtures/common fixtures/users;