# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_account_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='title',
        ),
    ]
