# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_auto_20160123_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finances.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='memo',
            field=models.TextField(null=True),
        ),
    ]
