# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_squashed_0004_email_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='start_sending',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='stop_sending',
            field=models.DateTimeField(null=True),
        ),
    ]
